Scripting orchestrator configuration

diff --git a/scripts/a4c_configure_orchestrator b/scripts/a4c_configure_orchestrator
--- a/scripts/a4c_configure_orchestrator
+++ b/scripts/a4c_configure_orchestrator
@@ -9,12 +9,21 @@
 #
 
 a4cURL="http://localhost:8088"
+yorcURL="http://localhost:8800"
 usage() {
     echo ""
     echo "Usage:"
-    echo "a4c_create_orchestrator.bash [--a4c-url <Alien4Cloud URL>]"
-    echo "   - default A4C URL        : $a4cURL"
+    echo "a4c_configure_orchestrator [--a4c-url <Alien4Cloud URL>] [--yorc-url <Yorc URL>]"
+    echo "   - default A4C URL : $a4cURL"
+    echo "   - default Yorc URL: $yorcURL"
     exit 1
+}
+
+getJsonval() {
+	jsonKey=$1
+	jsonContent=$2
+    temp=`echo "$jsonContent" | awk -F"[{,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$jsonKey'\042/){print $(i+1)}}}' | tr -d '"' | sed -n 1p`
+    echo $temp
 }
 
 POSITIONAL=()
@@ -25,6 +34,11 @@ key="$1"
 case $key in
     -a|--a4c-url)
     a4cURL="$2"
+    shift # past argument
+    shift # past value
+    ;;
+    -y|--yorc-url)
+    yorcURL="$2"
     shift # past argument
     shift # past value
     ;;
@@ -47,34 +61,33 @@ curl -d "username=admin&password=admin&submit=Login"  \
 	 --silent \
      --cookie-jar cookies.a4c
 
-# Check if a Yorc orchestrator already exists
-curl --request GET \
+# Get Orchestratror ID
+res=`curl --request GET \
          --url $a4cURL/rest/latest/orchestrators?query=Yorc \
          --header 'Accept: application/json' \
          --silent \
-         --cookie cookies.a4c \
-| grep --quiet Yorc
+         --cookie cookies.a4c`
+yorcID=`getJsonval id $res`
 
-res=$?
-if [ $res -eq 0 ]
-    then
-        echo "Orchestrator already created"
-        exit 0
+if [ -z "$yorcID" ]
+then
+    echo "Exiting on error getting the Orchestrator ID"
+    exit 1
 fi
 
-# Create the orchestrator
-curl --request POST \
-         --url $a4cURL/rest/latest/orchestrators \
+# Configure the orchestrator
+curl --request PUT \
+         --url $a4cURL/rest/latest/orchestrators/$yorcID/configuration  \
          --header 'Content-Type: application/json' \
          --cookie cookies.a4c \
          --silent \
-          --data "{\"name\": \"Yorc\", \"pluginId\": \"alien4cloud-yorc-plugin\", \"pluginBean\": \"yorc-orchestrator-factory\"}" > /dev/null
+          --data "{\"urlYorc\": \"$yorcURL\"}" > /dev/null
 
 res=$?
 if [ $res -ne 0 ]
 then
-    echo "Exiting on error creating the orchestrator in Alien4Cloud"
+    echo "Exiting on error configuring the orchestrator in Alien4Cloud"
     exit 1
 else
-    echo "Orchestrator created in Alien4Cloud"
+    echo "Orchestrator configured in Alien4Cloud"
 fi
