Added script to select a location

diff --git a/scripts/a4c_select_application_location b/scripts/a4c_select_application_location
--- a/scripts/a4c_select_application_location
+++ b/scripts/a4c_select_application_location
@@ -1,18 +1,20 @@
 #!/bin/bash
 
 #
-# a4c_set_application_inputs - Sets application input properties
+# a4c_select_application_location - Selects the location where to deply an application
 #
 
 a4cURL="http://localhost:8088"
 applicationName=""
-keyaluePairs=""
+locationName="google"
 usage() {
     echo ""
     echo "Usage:"
-    echo "a4c_set_application_inputs [--a4c-url <Alien4Cloud URL>] "
-    echo "                           --application <Application Name> --inputs \"key1=value1 key2=value2\""
-    echo "   - default A4C URL : $a4cURL"
+    echo "a4c_set_application_inputs --application <Application Name>"
+    echo "                           [--a4c-url <Alien4Cloud URL>]"
+    echo "                           [--location <Location Name>]"
+    echo "   - default A4C URL  : $a4cURL"
+    echo "   - default Location : $locationName"
 }
 
 getJsonval() {
@@ -43,7 +45,12 @@ case $key in
     shift # past argument
     shift # past value
     ;;
-    -h|--help)
+    -l|--location)
+    locationName="$2"
+    shift # past argument
+    shift # past value
+    ;;
+   -h|--help)
     usage
     exit 0
     ;;
@@ -69,6 +76,34 @@ curl -d "username=admin&password=admin&submit=Login"  \
 	 --silent \
      --cookie-jar cookies.a4c
 
+# Get Orchestratror ID
+res=`curl --request GET \
+         --url $a4cURL/rest/latest/orchestrators?query=Yorc \
+         --header 'Accept: application/json' \
+         --silent \
+         --cookie cookies.a4c`
+yorcID=`getJsonval id $res`
+
+if [ -z "$yorcID" ]
+then
+    echo "Exiting on error getting the Orchestrator ID"
+    exit 1
+fi
+
+# Get the location ID
+res=`curl --request GET \
+         --url $a4cURL/rest/latest/orchestrators/$yorcID/locations?query=Yorc \
+         --header 'Accept: application/json' \
+         --silent \
+         --cookie cookies.a4c`
+locationID=`getJsonval id $res`
+
+if [ -z "$locationID" ]
+then
+    echo "Exiting on error getting the ID for location $locationName"
+    exit 1
+fi
+
 # Get the Application environment ID
 res=`curl --request POST \
          --url $a4cURL/rest/latest/applications/environments \
@@ -84,35 +119,19 @@ then
     exit 1
 fi
 
-# Create the data to post
-inputData=""
-for keyValuePair in $keyaluePairs; do
-    set -- `echo $keyValuePair | tr '=' ' '`
-    key=$1
-    value=$2
-    newInput="\"$key\": \"$value\""
-    if [ -z "$inputData" ]
-    then
-        inputData="$newInput"
-    else
-        inputData="$inputData, $newInput"
-    fi
-done
-postData="{\"inputProperties\": {$inputData}}"
-
-# Set input parameters
-response=`curl --request PUT \
-         --url $a4cURL/rest/latest/applications/$applicationName/environments/$envID/deployment-topology \
+# Select the application deployment location
+response=`curl --request POST \
+         --url $a4cURL/rest/latest/applications/$applicationName/environments/$envID/deployment-topology/location-policies \
          --header 'Content-Type: application/json' \
          --cookie cookies.a4c \
          --silent \
-          --data "$postData"`
+          --data "{\"groupsToLocations\": {\"_A4C_ALL\": \"$locationID\"}, \"orchestratorId\": \"$yorcID\"}"`
 
 res=$?
 if [ $res -ne 0 ]
 then
-    echo "Exiting on error creating application $applicationName : $response"
+    echo "Exiting on error selecting location $locationName for application $applicationName : $response"
     exit 1
 fi
 
-echo "Input parameters set on Application $applicationName"
+echo "Selected location $locationName for application $applicationName"
